repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --config ./pyproject.toml .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config ./.flake8 .
        language: system
        types: [ python ]
        pass_filenames: false
