repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --config ./.black .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: flake8 --config ./setup.cfg .
        language: system
        types: [ python ]
        pass_filenames: false
