repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: blck --config ./setup.cfg .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: flake8
        name: flake8
        entry: blck --config ./setup.cfg .
        language: system
        types: [ python ]
        pass_filenames: false
