# Generated by Django 4.2.9 on 2024-02-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название задачи.",
                        max_length=256,
                        verbose_name="Название Задачи",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите подробное описание задачи.",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "deadline",
                    models.DateField(
                        help_text="Дата дедлайна не может быть раньше текущей.",
                        verbose_name="Дата дедлайна",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "В работе"),
                            ("not_done", "Не выполнен"),
                            ("absent", "Отсутствует"),
                            ("completed", "Выполнен"),
                            ("canceled", "Отменен"),
                        ],
                        default="in_progress",
                        max_length=16,
                        verbose_name="Статус задачи",
                    ),
                ),
                ("date_added", models.DateField(auto_now=True)),
                (
                    "lms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="lms.lms",
                        verbose_name="ИПР",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
            },
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("name", "lms"), name="unique_name_lms"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(("deadline__gte", models.F("date_added"))),
                name="deadline_must_be_after_date_added",
            ),
        ),
    ]
