# Generated by Django 4.2.9 on 2024-02-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "В работе"),
                    ("not_done", "Не выполнен"),
                    ("completed", "Выполнен"),
                    ("canceled", "Отменен"),
                ],
                default="in_progress",
                max_length=16,
                verbose_name="Статус задачи",
            ),
        ),
    ]
