# Generated by Django 4.2.9 on 2024-01-21 22:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название ИПР.",
                        max_length=256,
                        verbose_name="Название ИПР.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите подробное описание ИПР.",
                        verbose_name="Описание ИПР.",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "deadline",
                    models.DateField(
                        help_text="Дата дедлайна не может быть раньше текущей.",
                        verbose_name="Дата дедлайна.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("В работе", "in_progress"),
                            ("Не выполнен", "not_done"),
                            ("Выполнен", "completed"),
                            ("Отсутствует", "absent"),
                            ("Отменен", "canceled"),
                        ],
                        default="Отсутствует",
                        max_length=16,
                        verbose_name="Статус ИПР.",
                    ),
                ),
                (
                    "skill_assessment_before",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=0,
                                message="Не может быть меньше 0.",
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=0,
                                message="Не может быть больше 0.",
                            ),
                        ],
                        verbose_name="Оценка до.",
                    ),
                ),
                (
                    "skill_assessment_after",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(
                                limit_value=0,
                                message="Не может быть меньше 0.",
                            ),
                            django.core.validators.MaxValueValidator(
                                limit_value=0,
                                message="Не может быть больше 0.",
                            ),
                        ],
                        verbose_name="Оценка после.",
                    ),
                ),
                ("date_added", models.DateField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_lms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник.",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_lms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Руководитель.",
                    ),
                ),
            ],
            options={
                "verbose_name": "ИПР",
                "verbose_name_plural": "ИПР",
            },
        ),
        migrations.AddConstraint(
            model_name="lms",
            constraint=models.UniqueConstraint(
                fields=("employee", "supervisor", "name"),
                name="unique_employee_supervisor",
            ),
        ),
    ]
