# Generated by Django 4.2.9 on 2024-01-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lms",
            options={
                "ordering": ["-date_added"],
                "verbose_name": "ИПР",
                "verbose_name_plural": "ИПР",
            },
        ),
        migrations.AlterField(
            model_name="lms",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
