version: '3.3'

volumes:
  static_alpha:
  media_alpha:
  pg_data:

services:

  db:
    image: postgres:14
    env_file: ../config/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: prstud/alpha-backend:latest
    restart: always
    volumes:
      - static_alpha:/collected_static/
      - media_alpha:/backend/media/
    env_file:
      - ../config/.env
    command:
      - bash
      - -c
      - "gunicorn --bind 0.0.0.0:8000 config.wsgi"

  nginx:
    image: nginx:1.25.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_alpha:/var/html/static/
      - media_alpha:/var/html/media/
    depends_on:
      - backend
