version: '3.3'

volumes:
  static_alpha:
  media_alpha:
  pg_data:

services:

  db:
    image: postgres:14
    env_file: ../config/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: andreydogadkin/alpha-backend:latest
    restart: always
    env_file:
      - ../config/.env
    volumes:
      - static_alpha:/backend_static/
      - media_alpha:/backend/media/
    command: bash -c "
      python manage.py collectstatic
      && cp -r /app-backend/static/. /backend_static/static/
      && gunicorn --bind 0.0.0.0:8000 config.wsgi
      "

  nginx:
    image: nginx:1.25.0
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_alpha:/staticfiles/
      - media_alpha:/media/
    depends_on:
      - backend
