name: Flake8

on: [ pull_request ]
jobs:
  flake8_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip 
          pip install flake8
      - name: flake8 lint
        run: python -m flake8
